[general]
start_date = "2023-02-01"

[mongodb]
url = "mongodb+srv://USERNAME:PASSWORD@CLUSTER_URL/?retryWrites=true&w=majority"

[discord]
bot_token = "420692137@JPII.abc"
guild_id = "464786597288738816"
