[general]
start_date = "2023-02-01"
end_date = "2023-03-01"  # Optional, default value is the current date

[mongodb]
url = "mongodb+srv://USERNAME:PASSWORD@CLUSTER_URL/?retryWrites=true&w=majority"

[discord]
bot_token = "YOUR_BOT_TOKEN"
guild_id = "464786597288738816"

[twitter]
bearer_token = "BEARER_TOKEN"

[google]
secrets_file_path = "PATH TO THE .json FILE WITH CLIENT SECRETS"
